package com.erp.identity.infrastructure.validation

enum class ValidationErrorCode(
    val code: String,
) {
    TENANCY_INVALID_TENANT_ID("TENANCY_INVALID_TENANT_ID"),
    TENANCY_INVALID_ROLE_ID("TENANCY_INVALID_ROLE_ID"),
    TENANCY_INVALID_STATUS("TENANCY_INVALID_STATUS"),
    TENANCY_INVALID_PAGE_LIMIT("TENANCY_INVALID_PAGE_LIMIT"),
    TENANCY_INVALID_PAGE_OFFSET("TENANCY_INVALID_PAGE_OFFSET"),
}
