package com.erp.apigateway.validation

enum class GatewayValidationErrorCode(
    val code: String,
) {
    GATEWAY_INVALID_TENANT_ID("GATEWAY_INVALID_TENANT_ID"),
    GATEWAY_INVALID_PATTERN("GATEWAY_INVALID_PATTERN"),
    GATEWAY_INVALID_REQUESTS_PER_MINUTE("GATEWAY_INVALID_REQUESTS_PER_MINUTE"),
    GATEWAY_INVALID_WINDOW_SECONDS("GATEWAY_INVALID_WINDOW_SECONDS"),
}
